name: testworkflow
on: 
 push:
   branches:
    - main

jobs:
 build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.2.0
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2
      - name: restore nuget packages
        run: nuget restore
      - name: build project
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: drop
          path: '/published/**'
     
       
